### ISSUE TITLE
Asus Rog Strix B450-F NOT Detected

### ISSUE THREAD

**Issue by Thedabest** [DarthAffe/RGBSyncPlus#25]
![image](https://user-images.githubusercontent.com/40519768/51438930-7d7ddd80-1ce5-11e9-9024-4690383a1306.png)
AURA SYNC installed :(

**Comment by tanisdlj** [comment]
Maybe this helps:

In this link ( http://forum.corsair.com/v3/showthread.php?t=180890 ) DarthAffe says that you will need Aura version 1.06.17. 

If you have another version of Aura apparently you will need to uninstall it using CCleaner and then install that specific version of Aura. 

Otherwise it might now work, as ASUS standard uninstaller leaves some files behind and even after installing the older version won't work.

Do you have the recommended version? :)
